name: "CD: Deploy to Prod"

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      DATABRICKS_SP_NAME: ${{ secrets.DATABRICKS_SP_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate bundle
        run: databricks bundle validate -t prod

      - name: Deploy to prod
        run: databricks bundle deploy -t prod

      - name: Run pipeline
        run: databricks bundle run pella_parts_forecasting -t prod
